# -*- coding: utf-8 -*-
"""team virus final project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123nQuxnJUycIz3iJpKqvnRs52AMoWUfA
"""

import pygame
import sys
import random
import math

pygame.init()
pygame.display.set_caption("Team Virus Arcade Hub")

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60

BLACK = (5, 10, 5)
NEON_GREEN = (51, 255, 51)
DARK_GREEN = (0, 100, 0)
WHITE = (200, 255, 200)
RED = (255, 50, 50)

screen = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
clock = pygame.time.Clock()

try:
    font_title = pygame.font.SysFont("impact", 50)
    font_menu = pygame.font.SysFont("monospace", 30)
    font_small = pygame.font.SysFont("monospace", 20)
except:
    font_title = pygame.font.Font(None, 50)
    font_menu = pygame.font.Font(None, 30)
    font_small = pygame.font.Font(None, 20)

def draw_text(text, font, color, surface, x, y, center=True):
    textobj = font.render(text, True, color)
    textrect = textobj.get_rect()
    if center:
        textrect.center = (x, y)
    else:
        textrect.topleft = (x, y)
    surface.blit(textobj, textrect)

def draw_button(text, x, y, w, h, active=False):
    color = NEON_GREEN if active else DARK_GREEN
    text_color = BLACK if active else NEON_GREEN
    pygame.draw.rect(screen, color, (x, y, w, h), border_radius=5)
    pygame.draw.rect(screen, NEON_GREEN, (x, y, w, h), 2, border_radius=5)
    draw_text(text, font_menu, text_color, screen, x + w//2, y + h//2)
    return pygame.Rect(x, y, w, h)

def game_snake():
    cell_size = 20
    snake = [(100, 100), (80, 100), (60, 100)]
    direction = (cell_size, 0)
    food = (random.randrange(0, SCREEN_WIDTH//cell_size) * cell_size,
            random.randrange(0, SCREEN_HEIGHT//cell_size) * cell_size)
    score = 0
    game_over = False

    while True:
        screen.fill(BLACK)

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit(); sys.exit()
            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE:
                    return
                if not game_over:
                    if event.key == pygame.K_UP and direction != (0, cell_size):
                        direction = (0, -cell_size)
                    elif event.key == pygame.K_DOWN and direction != (0, -cell_size):
                        direction = (0, cell_size)
                    elif event.key == pygame.K_LEFT and direction != (cell_size, 0):
                        direction = (-cell_size, 0)
                    elif event.key == pygame.K_RIGHT and direction != (-cell_size, 0):
                        direction = (cell_size, 0)
                elif event.key == pygame.K_r:
                    game_snake()
                    return

        if not game_over:
            new_head = (snake[0][0] + direction[0], snake[0][1] + direction[1])

            if (new_head[0] < 0 or new_head[0] >= SCREEN_WIDTH or
                new_head[1] < 0 or new_head[1] >= SCREEN_HEIGHT):
                game_over = True

            if new_head in snake:
                game_over = True

            snake.insert(0, new_head)

            if new_head == food:
                score += 10
                food = (random.randrange(0, SCREEN_WIDTH//cell_size) * cell_size,
                        random.randrange(0, SCREEN_HEIGHT//cell_size) * cell_size)
            else:
                snake.pop()

        for segment in snake:
            pygame.draw.rect(screen, NEON_GREEN, (segment[0], segment[1], cell_size-2, cell_size-2))

        pygame.draw.rect(screen, RED, (food[0], food[1], cell_size, cell_size))

        draw_text(f"Score: {score}", font_small, WHITE, screen, 50, 20)
        draw_text("ESC to Exit", font_small, WHITE, screen, SCREEN_WIDTH - 60, 20)

        if game_over:
            draw_text("GAME OVER", font_title, RED, screen, SCREEN_WIDTH//2, SCREEN_HEIGHT//2)
            draw_text("Press 'R' to Restart or ESC to Menu", font_menu, WHITE, screen, SCREEN_WIDTH//2, SCREEN_HEIGHT//2 + 50)

        pygame.display.update()
        clock.tick(10)

def game_pong():
    paddle_w, paddle_h = 15, 90
    ball_size = 15

    player_y = SCREEN_HEIGHT//2 - paddle_h//2
    opponent_y = SCREEN_HEIGHT//2 - paddle_h//2
    ball_x, ball_y = SCREEN_WIDTH//2, SCREEN_HEIGHT//2
    ball_dx, ball_dy = 5 * random.choice((1, -1)), 5 * random.choice((1, -1))

    player_score = 0
    ai_score = 0

    while True:
        screen.fill(BLACK)
        pygame.draw.line(screen, DARK_GREEN, (SCREEN_WIDTH//2, 0), (SCREEN_WIDTH//2, SCREEN_HEIGHT), 2)

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit(); sys.exit()
            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE: return

        dy = 0
        keys = pygame.key.get_pressed()

        if keys[pygame.K_w] or keys[pygame.K_UP]:
            dy -= 7
        if keys[pygame.K_s] or keys[pygame.K_DOWN]:
            dy += 7

        player_y += dy
        player_y = max(0, min(SCREEN_HEIGHT - paddle_h, player_y))

        if opponent_y + paddle_h//2 < ball_y:
            opponent_y += 5
        elif opponent_y + paddle_h//2 > ball_y:
            opponent_y -= 5
        opponent_y = max(0, min(SCREEN_HEIGHT - paddle_h, opponent_y))

        ball_x += ball_dx
        ball_y += ball_dy

        if ball_y <= 0 or ball_y >= SCREEN_HEIGHT - ball_size:
            ball_dy *= -1

        player_rect = pygame.Rect(50, player_y, paddle_w, paddle_h)
        opponent_rect = pygame.Rect(SCREEN_WIDTH - 50 - paddle_w, opponent_y, paddle_w, paddle_h)
        ball_rect = pygame.Rect(ball_x, ball_y, ball_size, ball_size)

        if ball_rect.colliderect(player_rect) or ball_rect.colliderect(opponent_rect):
            ball_dx *= -1.1

        if ball_x < 0:
            ai_score += 1
            ball_x, ball_y = SCREEN_WIDTH//2, SCREEN_HEIGHT//2
            ball_dx = 5
        elif ball_x > SCREEN_WIDTH:
            player_score += 1
            ball_x, ball_y = SCREEN_WIDTH//2, SCREEN_HEIGHT//2
            ball_dx = -5

        pygame.draw.rect(screen, NEON_GREEN, player_rect)
        pygame.draw.rect(screen, RED, opponent_rect)
        pygame.draw.ellipse(screen, WHITE, ball_rect)

        draw_text(f"{player_score}", font_title, NEON_GREEN, screen, SCREEN_WIDTH//4, 50)
        draw_text(f"{ai_score}", font_title, RED, screen, 3*SCREEN_WIDTH//4, 50)
        draw_text("Arrows/WS to Move - ESC to Exit", font_small, WHITE, screen, SCREEN_WIDTH//2, SCREEN_HEIGHT - 20)

        pygame.display.update()
        clock.tick(60)

def game_space_invaders():
    player_w, player_h = 40, 20
    player_x = SCREEN_WIDTH//2
    player_y = SCREEN_HEIGHT - 50
    bullets = []
    enemies = []
    enemy_rows = 4
    enemy_cols = 8

    for r in range(enemy_rows):
        for c in range(enemy_cols):
            enemies.append(pygame.Rect(100 + c * 70, 50 + r * 50, 40, 30))

    enemy_dx = 2
    game_over = False
    win = False

    while True:
        screen.fill(BLACK)

        for event in pygame.event.get():
            if event.type == pygame.QUIT: pygame.quit(); sys.exit()
            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE: return
                if event.key == pygame.K_SPACE and not game_over and not win:
                    bullets.append(pygame.Rect(player_x + player_w//2 - 2, player_y, 4, 10))
                if (game_over or win) and event.key == pygame.K_r:
                    game_space_invaders(); return

        keys = pygame.key.get_pressed()
        if keys[pygame.K_LEFT]: player_x -= 5
        if keys[pygame.K_RIGHT]: player_x += 5
        player_x = max(0, min(SCREEN_WIDTH - player_w, player_x))

        if not game_over and not win:
            for b in bullets[:]:
                b.y -= 7
                if b.y < 0: bullets.remove(b)

            move_down = False
            for e in enemies:
                e.x += enemy_dx
                if e.x <= 0 or e.right >= SCREEN_WIDTH:
                    move_down = True

            if move_down:
                enemy_dx *= -1
                for e in enemies: e.y += 20

            for b in bullets[:]:
                for e in enemies[:]:
                    if b.colliderect(e):
                        bullets.remove(b)
                        enemies.remove(e)
                        break

            if not enemies: win = True
            for e in enemies:
                if e.y > player_y - 20:
                    game_over = True

        points = [(player_x, player_y + player_h), (player_x + player_w//2, player_y), (player_x + player_w, player_y + player_h)]
        pygame.draw.polygon(screen, NEON_GREEN, points)

        for e in enemies:
            pygame.draw.rect(screen, RED, e)
            pygame.draw.circle(screen, BLACK, (e.x + 10, e.y + 10), 3)
            pygame.draw.circle(screen, BLACK, (e.x + 30, e.y + 10), 3)

        for b in bullets:
            pygame.draw.rect(screen, WHITE, b)

        if game_over:
            draw_text("MISSION FAILED", font_title, RED, screen, SCREEN_WIDTH//2, SCREEN_HEIGHT//2)
            draw_text("Press 'R' to Retry", font_menu, WHITE, screen, SCREEN_WIDTH//2, SCREEN_HEIGHT//2 + 50)
        elif win:
            draw_text("MISSION ACCOMPLISHED", font_title, NEON_GREEN, screen, SCREEN_WIDTH//2, SCREEN_HEIGHT//2)
            draw_text("Press 'R' to Retry", font_menu, WHITE, screen, SCREEN_WIDTH//2, SCREEN_HEIGHT//2 + 50)

        draw_text("Arrows to Move - Space to Shoot - ESC to Exit", font_small, WHITE, screen, SCREEN_WIDTH//2, SCREEN_HEIGHT - 20)
        pygame.display.update()
        clock.tick(60)

def game_flappy_bird():
    bird_y = SCREEN_HEIGHT // 2
    bird_x = 100
    bird_vel = 0
    gravity = 0.5
    jump_strength = -8

    pipes = []
    pipe_width = 50
    pipe_gap = 150
    spawn_timer = 0

    score = 0
    game_over = False
    waiting = True

    while True:
        screen.fill(BLACK)

        for event in pygame.event.get():
            if event.type == pygame.QUIT: pygame.quit(); sys.exit()
            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE: return
                if event.key == pygame.K_SPACE:
                    if waiting:
                        waiting = False
                        bird_vel = jump_strength
                    elif not game_over:
                        bird_vel = jump_strength

                if game_over and event.key == pygame.K_r:
                    game_flappy_bird(); return

        if not waiting and not game_over:
            bird_vel += gravity
            bird_y += bird_vel

            spawn_timer += 1
            if spawn_timer > 90:
                height = random.randint(100, 400)
                pipes.append([SCREEN_WIDTH, height, False])
                spawn_timer = 0

            bird_rect = pygame.Rect(bird_x, bird_y, 30, 30)

            for p in pipes:
                p[0] -= 3

                top_rect = pygame.Rect(p[0], 0, pipe_width, p[1])
                bottom_rect = pygame.Rect(p[0], p[1] + pipe_gap, pipe_width, SCREEN_HEIGHT - (p[1] + pipe_gap))

                if bird_rect.colliderect(top_rect) or bird_rect.colliderect(bottom_rect):
                    game_over = True

                if not p[2] and p[0] < bird_x:
                    score += 1
                    p[2] = True

            if pipes and pipes[0][0] < -pipe_width:
                pipes.pop(0)

            if bird_y > SCREEN_HEIGHT or bird_y < 0:
                game_over = True

        for p in pipes:
            pygame.draw.rect(screen, NEON_GREEN, (p[0], 0, pipe_width, p[1]))
            pygame.draw.rect(screen, NEON_GREEN, (p[0], p[1] + pipe_gap, pipe_width, SCREEN_HEIGHT))
            pygame.draw.rect(screen, DARK_GREEN, (p[0]-2, p[1]-20, pipe_width+4, 20))
            pygame.draw.rect(screen, DARK_GREEN, (p[0]-2, p[1] + pipe_gap, pipe_width+4, 20))

        pygame.draw.rect(screen, (255, 255, 0), (bird_x, bird_y, 30, 30))
        pygame.draw.rect(screen, WHITE, (bird_x+20, bird_y+5, 10, 10))

        draw_text(f"Score: {score}", font_title, WHITE, screen, SCREEN_WIDTH//2, 50)

        if waiting:
             draw_text("PRESS SPACE TO START", font_title, NEON_GREEN, screen, SCREEN_WIDTH//2, SCREEN_HEIGHT//2)

        if game_over:
            draw_text("CRASHED!", font_title, RED, screen, SCREEN_WIDTH//2, SCREEN_HEIGHT//2)
            draw_text("Press 'R' to Retry or ESC to Menu", font_menu, WHITE, screen, SCREEN_WIDTH//2, SCREEN_HEIGHT//2 + 50)

        draw_text("Space to Jump - ESC to Exit", font_small, WHITE, screen, SCREEN_WIDTH//2, SCREEN_HEIGHT - 20)
        pygame.display.update()
        clock.tick(60)

def main_menu():
    click = False

    matrix_drops = [random.randint(0, SCREEN_HEIGHT) for _ in range(0, SCREEN_WIDTH, 20)]

    while True:
        screen.fill(BLACK)

        for i in range(len(matrix_drops)):
            char = random.choice(["0", "1", "V", "I", "R", "U", "S"])
            draw_text(char, font_small, DARK_GREEN, screen, i*20, matrix_drops[i], center=False)
            matrix_drops[i] += 10
            if matrix_drops[i] > SCREEN_HEIGHT:
                matrix_drops[i] = random.randint(-100, 0)

        s = pygame.Surface((600, 500))
        s.set_alpha(200)
        s.fill((0, 0, 0))
        screen.blit(s, (100, 50))

        pygame.draw.rect(screen, NEON_GREEN, (100, 50, 600, 500), 3)

        draw_text("TEAM VIRUS ARCADE", font_title, NEON_GREEN, screen, SCREEN_WIDTH//2, 100)
        draw_text("Batch 33 | Team 03", font_small, WHITE, screen, SCREEN_WIDTH//2, 150)

        mx, my = pygame.mouse.get_pos()

        btn_snake = draw_button("1. SNAKE GAME", 250, 200, 300, 50, 250 < mx < 550 and 200 < my < 250)
        btn_pong = draw_button("2. PONG", 250, 270, 300, 50, 250 < mx < 550 and 270 < my < 320)
        btn_space = draw_button("3. SPACE INVADERS", 250, 340, 300, 50, 250 < mx < 550 and 340 < my < 390)
        btn_bird = draw_button("4. FLAPPY BIRD", 250, 410, 300, 50, 250 < mx < 550 and 410 < my < 460)

        click = False
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit(); sys.exit()
            if event.type == pygame.MOUSEBUTTONDOWN:
                if event.button == 1: click = True

        if click:
            if btn_snake.collidepoint((mx, my)): game_snake()
            if btn_pong.collidepoint((mx, my)): game_pong()
            if btn_space.collidepoint((mx, my)): game_space_invaders()
            if btn_bird.collidepoint((mx, my)): game_flappy_bird()

        draw_text("Select a game to start", font_small, WHITE, screen, SCREEN_WIDTH//2, 520)

        pygame.display.update()
        clock.tick(60)

if __name__ == "__main__":
    main_menu()